name: Update Birthdays HTML

on:
  schedule:
    - cron: "0 22 * * *"  # magyar idő szerint 00:00 (nyáron)
  workflow_dispatch:       # kézi indítás lehetősége

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - name: Repo letöltése
        uses: actions/checkout@v4

      - name: Python környezet beállítása
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Függőségek telepítése
        run: |
          pip install gspread google-auth

      - name: Születésnapos HTML generálása
        env:
          GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}
        run: python update_birthdays.py

      - name: Változások commitolása és feltöltése
        run: |
          git config user.name "GitHub Action"
          git config user.email "actions@github.com"
          git add birthday_widget.html
          git commit -m "Auto-update birthday widget" || echo "Nincs commitálnivaló"
          git push
